version: "3.8"

services:
  db:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_USER: moneywise
      POSTGRES_PASSWORD: moneywise_password
      POSTGRES_DB: moneywise_db
    ports:
      - "5432:5432"
    volumes:
      - moneywise_postgres_data:/var/lib/postgresql/data

volumes:
  moneywise_postgres_data:
