services:
  postgres:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=moneywise
      - POSTGRES_PASSWORD=moneywise_password
      - POSTGRES_DB=moneywise_db
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - '5432:5432'

volumes:
  postgres: